apiVersion: v1
kind: Pod
metadata:
  name: exampl-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - name: almalinux
    image: almalinux:9    
    command: ["sleep", "2000"]
    volumeMounts:
    - mountPath: nginx-logs
      name: /mnt/nginx-logs      
      readOnly: true
  # this is pod level
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi