apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: roboshop-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-dynamic-v
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic-v
      persistentVolumeClaim:
        claimName: efs-dynamic