apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    imageregistery: "http://hub.docker.com"
    githuburl: "https://github.com/e-shekharreddy/k8s-resources"
  labels:
    name: roboshop
    environment: dev
    component: frontend
spec:
- name: nginx
  image: nginx